// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto3.Infrastructure.Data;

#nullable disable

namespace Proyecto3.Infrastructure.Migrations
{
    [DbContext(typeof(TalentoInternoDbContext))]
    [Migration("20251128211758_SetProgresoPorcentajePrecision")]
    partial class SetProgresoPorcentajePrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto3.Core.Entities.Beneficio", b =>
                {
                    b.Property<int>("BeneficioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeneficioID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BeneficioID");

                    b.ToTable("Beneficios");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Certificacion", b =>
                {
                    b.Property<int>("CertificacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificacionID"));

                    b.Property<int>("ColaboradorID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaObtencion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCertificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CertificacionID");

                    b.HasIndex("ColaboradorID");

                    b.ToTable("Certificaciones");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Colaborador", b =>
                {
                    b.Property<int>("ColaboradorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColaboradorID"));

                    b.Property<string>("CuentaProyecto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisponibilidadMovilidad")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColaboradorID");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Curso", b =>
                {
                    b.Property<int>("CursoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionHoras")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CursoID");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.HabilidadColaborador", b =>
                {
                    b.Property<int>("ColaboradorID")
                        .HasColumnType("int");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaUltimaEvaluacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NivelDominio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColaboradorID", "SkillID");

                    b.HasIndex("SkillID");

                    b.ToTable("HabilidadesColaboradores");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Notificacion", b =>
                {
                    b.Property<int>("NotificacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacionID"));

                    b.Property<int>("ColaboradorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificacionID");

                    b.HasIndex("ColaboradorID");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Perfil", b =>
                {
                    b.Property<int>("PerfilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerfilID"));

                    b.Property<int>("ColaboradorID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PerfilCompleto")
                        .HasColumnType("bit");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PerfilID");

                    b.HasIndex("ColaboradorID");

                    b.ToTable("Perfiles");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.PerfilesVacante", b =>
                {
                    b.Property<int>("VacanteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VacanteID"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUrgencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NivelDeseado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VacanteID");

                    b.ToTable("PerfilesVacante");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Progreso_Curso", b =>
                {
                    b.Property<int>("ProgresoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgresoID"));

                    b.Property<int>("ColaboradorID")
                        .HasColumnType("int");

                    b.Property<bool>("Completado")
                        .HasColumnType("bit");

                    b.Property<int>("CursoID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCompletacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PorcentajeCompletacion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ProgresoID");

                    b.HasIndex("ColaboradorID");

                    b.HasIndex("CursoID");

                    b.ToTable("ProgresoCursos");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Punto", b =>
                {
                    b.Property<int>("PuntoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PuntoID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ColaboradorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaOtorgamiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Razon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalAcumulado")
                        .HasColumnType("int");

                    b.HasKey("PuntoID");

                    b.HasIndex("ColaboradorID");

                    b.ToTable("Puntos");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.RequisitoVacante", b =>
                {
                    b.Property<int>("RequisitoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequisitoID"));

                    b.Property<string>("NivelMinimoRequerido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.Property<int>("VacanteID")
                        .HasColumnType("int");

                    b.HasKey("RequisitoID");

                    b.HasIndex("SkillID");

                    b.HasIndex("VacanteID");

                    b.ToTable("RequisitosVacante");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillID"));

                    b.Property<string>("NombreSkill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoSkill")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Vacante_Aplicacion", b =>
                {
                    b.Property<int>("AplicacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AplicacionID"));

                    b.Property<int>("ColaboradorID")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Interes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VacanteID")
                        .HasColumnType("int");

                    b.HasKey("AplicacionID");

                    b.HasIndex("ColaboradorID");

                    b.HasIndex("VacanteID");

                    b.ToTable("VacanteAplicaciones");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Certificacion", b =>
                {
                    b.HasOne("Proyecto3.Core.Entities.Colaborador", "Colaborador")
                        .WithMany("Certificaciones")
                        .HasForeignKey("ColaboradorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.HabilidadColaborador", b =>
                {
                    b.HasOne("Proyecto3.Core.Entities.Colaborador", "Colaborador")
                        .WithMany("Habilidades")
                        .HasForeignKey("ColaboradorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto3.Core.Entities.Skill", "Skill")
                        .WithMany("HabilidadesColaboradores")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Notificacion", b =>
                {
                    b.HasOne("Proyecto3.Core.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Perfil", b =>
                {
                    b.HasOne("Proyecto3.Core.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Progreso_Curso", b =>
                {
                    b.HasOne("Proyecto3.Core.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto3.Core.Entities.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Punto", b =>
                {
                    b.HasOne("Proyecto3.Core.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.RequisitoVacante", b =>
                {
                    b.HasOne("Proyecto3.Core.Entities.Skill", "Skill")
                        .WithMany("RequisitosVacantes")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto3.Core.Entities.PerfilesVacante", "Vacante")
                        .WithMany("RequisitosVacante")
                        .HasForeignKey("VacanteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Vacante_Aplicacion", b =>
                {
                    b.HasOne("Proyecto3.Core.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto3.Core.Entities.PerfilesVacante", "Vacante")
                        .WithMany()
                        .HasForeignKey("VacanteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Colaborador", b =>
                {
                    b.Navigation("Certificaciones");

                    b.Navigation("Habilidades");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.PerfilesVacante", b =>
                {
                    b.Navigation("RequisitosVacante");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Skill", b =>
                {
                    b.Navigation("HabilidadesColaboradores");

                    b.Navigation("RequisitosVacantes");
                });
#pragma warning restore 612, 618
        }
    }
}
