// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto3.Infrastructure.Data;

#nullable disable

namespace Proyecto3.Infrastructure.Migrations
{
    [DbContext(typeof(TalentoInternoDbContext))]
    partial class TalentoInternoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto3.Core.Entities.Certificacion", b =>
                {
                    b.Property<int>("CertificacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificacionID"));

                    b.Property<int>("ColaboradorID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaObtencion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCertificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CertificacionID");

                    b.HasIndex("ColaboradorID");

                    b.ToTable("Certificaciones");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Colaborador", b =>
                {
                    b.Property<int>("ColaboradorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColaboradorID"));

                    b.Property<string>("CuentaProyecto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisponibilidadMovilidad")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColaboradorID");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.HabilidadColaborador", b =>
                {
                    b.Property<int>("ColaboradorID")
                        .HasColumnType("int");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaUltimaEvaluacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NivelDominio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColaboradorID", "SkillID");

                    b.HasIndex("SkillID");

                    b.ToTable("HabilidadesColaboradores");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.PerfilesVacante", b =>
                {
                    b.Property<int>("VacanteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VacanteID"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUrgencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NivelDeseado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VacanteID");

                    b.ToTable("PerfilesVacante");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.RequisitoVacante", b =>
                {
                    b.Property<int>("RequisitoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequisitoID"));

                    b.Property<string>("NivelMinimoRequerido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.Property<int>("VacanteID")
                        .HasColumnType("int");

                    b.HasKey("RequisitoID");

                    b.HasIndex("SkillID");

                    b.HasIndex("VacanteID");

                    b.ToTable("RequisitosVacante");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillID"));

                    b.Property<string>("NombreSkill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoSkill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Certificacion", b =>
                {
                    b.HasOne("Proyecto3.Core.Entities.Colaborador", "Colaborador")
                        .WithMany("Certificaciones")
                        .HasForeignKey("ColaboradorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.HabilidadColaborador", b =>
                {
                    b.HasOne("Proyecto3.Core.Entities.Colaborador", "Colaborador")
                        .WithMany("Habilidades")
                        .HasForeignKey("ColaboradorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto3.Core.Entities.Skill", "Skill")
                        .WithMany("HabilidadesColaboradores")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.RequisitoVacante", b =>
                {
                    b.HasOne("Proyecto3.Core.Entities.Skill", "Skill")
                        .WithMany("RequisitosVacantes")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto3.Core.Entities.PerfilesVacante", "Vacante")
                        .WithMany("RequisitosVacante")
                        .HasForeignKey("VacanteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Colaborador", b =>
                {
                    b.Navigation("Certificaciones");

                    b.Navigation("Habilidades");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.PerfilesVacante", b =>
                {
                    b.Navigation("RequisitosVacante");
                });

            modelBuilder.Entity("Proyecto3.Core.Entities.Skill", b =>
                {
                    b.Navigation("HabilidadesColaboradores");

                    b.Navigation("RequisitosVacantes");
                });
#pragma warning restore 612, 618
        }
    }
}
